### ISSUE TITLE
How to modify the bash (or partially use these bash) to create PDBbind2019 Refined types file (Crystal&Docked)?

### ISSUE THREAD

**Issue by JonasLi-19** [RMeli/gsoc19#1]
Dear @RMeli, I have noticed you are an expert on this area in the gnina program.
It is surprising to find that you develop this gsoc19 repository for us to quickly extract and generates files for PDBbind, which will be very helpful.
I try to use gnina to train the model on docked poses data of PDBbind2019 refined-set generated by gnina before, how can I make Crystal types and Docked types respectly through your scripts? I couldn't find how to assign the affnity, rmsd and label into the types file...

**Comment by RMeli** [comment]
Hi @JonasLi-19. 

This repository was used to create a data set obtained with docking with flexible residues (often shortened to flexible docking) and to train GNINA models with said data set. 

You will need to carefully read the documentation and the scripts (the best documentation is the code itself!) in order to understand if some scripts can be useful for your project. Some scripts might not be that flexible and will need to be heavily adapted to your workflow.

> how can I make Crystal types

I'm not sure what do you mean with "Crystal types". In this repository, "Crystal" usually denotes the crystal structure optimized (locally) with the AutoDock Vina scoring function (as implemented in GNINA).

You can find details about generating Vina-minimized crystal poses in `redocking/optimisation/`. In particular, you might want to have a look at the `01_optimisation.sh` script:

https://github.com/RMeli/gsoc19/blob/01a7a89470a7b66cceb0c6eef499cfb06af21a93/redocking/optimisation/01_optimisation.sh#L46-L51 

*Note: for historical reasons I used `smina` to perform this minimization, but `gnina` is equivalent with the `--cnn_scoring none` option.

> how can I make Docked types

Again I'm not sure what do you mean exactly with "Docked types", but if you mean multiple docked poses obtained with the AutoDock Vina scoring function (as implemented in GNINA) then you should look at the details in `redocking/docking/`. In particular, you might want to have a look at the `docking.sh` script:

https://github.com/RMeli/gsoc19/blob/01a7a89470a7b66cceb0c6eef499cfb06af21a93/redocking/docking/docking.sh#L40-L45

*Note: for historical reasons I used `smina` to perform this minimization, but `gnina` is equivalent with the `--cnn_scoring none` option.

> I couldn't find how to assign the affnity, rmsd and label into the types file

The `.types` file needed by GNINA for training is of the following form:

```
LABEL AFFINITY RMSD PATH_TO_PROTEIN_FILE PATH_TO_LIGAND_FILE
```

The `AFFINITY` and `RMSD` might or might not be present depending on the model you are training. It is up to you to create this file with your data.

You can have a look at `redocking/mltraining` for more details.

For this project, this file is created by `03_buildtypefile.sh`:

https://github.com/RMeli/gsoc19/blob/01a7a89470a7b66cceb0c6eef499cfb06af21a93/redocking/mltraining/03_buildtypefile.sh#L23-L29

You can have a look at `scripts/python/buildtypefile.py` to see the Python script that is actually generating the file. As mentioned above, this is tailored for this particular project involving docking with flexible residues, therefore you will have to change it to your needs.

---

I hope this helps. Please have a look at the `README.md` files which describe the different steps. (These files are written assuming a familiarity with the [relevant literature for GNINA](https://github.com/gnina/gnina#citation).) Together with the code within the actual scripts, they should give you a solid starting point for your own project.
